# 配置端口
server:
  port: 8084
# 配置数据源
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=IEIS_SPC
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: sqlserver


  redis:
    host: localhost
    port: 6379
    #客户端超时时间单位是毫秒 默认是2000
    timeout: 1000

#      pool:
#        max-active: 20
#        max-idle: 8
#        min-idle: 2
#        max-wait: 100



mybatis:
  mapper-locations: classpath:mappers/*.xml